GET http://localhost:3000/products HTTP/1.1

###
//GET http://localhost:3000/products/3 HTTP/1.1
PUT http://localhost:3000/products/1 HTTP/1.1
Content-Type: application/json

{
    "total_amount": "10.00"
}
//DELETE http://localhost:3000/products/3 HTTP/1.1
//Content-Type: application/json
###

POST http://localhost:3000/products
Content-Type: application/json



{
    "issue_date": "2025-01-23T00:00:00.000Z",
    "total_amount": "8.00",
    "payment_status": "Pendiente",
    "notification_sent": 0
}

###
